# Generated by Django 6.0.7 on 2026-07-18 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
